host: 0.0.0.0
port: 8088
server: http://localhost

globalVariables:
  defaultLanguage: en
  supportLanguages: # use value in i18n.js
    - en
    - zh-hans
    - ko-kr
  product_name: { en: 'Qumulus Cloud Platform' }
  title: { en: 'Qumulus Cloud Platform' }
  keystoneUrl: https://cloud.qumulus.io:5000
  keycloakUrl: https://auth.qumulus.io
  keycloakRealm: qumulus
