host: 0.0.0.0
port: 8088
server: http://127.0.0.1:28000
theme: default

theme: default

globalVariables:
  defaultLanguage: en
  supportLanguages: # use value in i18n.js
    - en
    - zh-hans
    - ko-kr
<<<<<<< Updated upstream
    - ru
=======
    - ru
>>>>>>> Stashed changes
